options:
    testing:
        save_images: false
    image_dir: images
    kernel_dir: kernels
    test_dir: test_input
    output_dir: output
    log_level: WARN
execute:
    - operation: convolve
      kernel: identity.txt
      source: lena.png
      output: lena.png
    - operation: convolve
      kernel: sobel.txt
      source: lena.png
      output: sobel.png
    - operation: reduce
      source: lena.png
      output: reduced.png
    - operation: expand
      source: lena.png
      output: expanded.png
    - pipeline:
          - operation: reduce
          - operation: convolve
            kernel: sobel.txt
          - operation: expand
      source: lena.png
      output: reduced_convolved_expanded.png
